# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: deploy release

on:
  push:
    tags:
      - v*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_VPC_ID: vpc-0499f07d75deb3d4e
  AWS_SUBNET_ID: subnet-016c385fd35de887a
  AWS_DEFAULT_REGION: us-east-1
  DIST_HOME: ${{ environment.DIST_HOME }}
  DIST_DIR: ${{ github.sha }}
  SERVER_NAME: 'pierogis.live'

jobs:
  environment: dev
  deploy-develop-build:
    if: github.ref == 'refs/heads/main'
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run:
          pip install fabric
          python setup.py develop

      - name: build
        run: |
          fab build

      - name: upload to aws
        shell: bash
        run: |
          pip install -U awscli
          python -m awscli s3 sync --exact-timestamps ./dist "s3://$DIST_HOME/$DIST_DIR"

      - name: deploy
        run: |
          fab launch --stage=live --count=1
                    fab bootstrap --stage=live
                    fab deploy --stage=live